# Generated by Django 2.0.2 on 2018-03-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visite_virtuelle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visite',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
