# Generated by Django 2.0.2 on 2018-03-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visite_virtuelle', '0002_visite_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visite',
            name='visite',
            field=models.FileField(upload_to=''),
        ),
    ]
