# Generated by Django 2.0.2 on 2018-03-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visite_virtuelle', '0003_auto_20180306_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visite',
            name='visite',
            field=models.URLField(),
        ),
    ]
