# Generated by Django 2.0.2 on 2018-03-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.URLField()),
                ('name', models.CharField(default='', max_length=200)),
            ],
            options={
                'verbose_name': 'Site Web',
            },
        ),
    ]
