# Generated by Django 2.0.2 on 2018-03-03 21:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('photographe', models.CharField(max_length=42)),
                ('contenu', models.TextField(null=True)),
                ('url', models.CharField(max_length=400)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'photo',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40)),
                ('details', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galerie_photo.Theme'),
        ),
    ]
