# Generated by Django 2.0.2 on 2018-03-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerie_photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='contenu',
            field=models.TextField(blank=True, null=True),
        ),
    ]
