# Generated by Django 2.0.2 on 2018-03-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerie_photo', '0003_auto_20180305_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='url',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
    ]
