# Generated by Django 2.0.2 on 2018-03-06 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galerie_photo', '0004_auto_20180306_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='url',
        ),
    ]
