# Generated by Django 2.0.2 on 2018-03-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerie_photo', '0005_remove_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='contenu',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
