# Generated by Django 2.0.2 on 2018-03-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerie_photo', '0008_auto_20180306_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='details',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
