# Generated by Django 2.0.2 on 2018-03-07 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('galerie_photo', '0009_auto_20180306_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('galerie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galerie_photo.Theme')),
            ],
            options={
                'verbose_name': 'table',
            },
        ),
    ]
