# Generated by Django 2.0.2 on 2018-03-07 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_table', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='galerie',
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
