# Generated by Django 2.0.2 on 2018-03-07 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('visite_virtuelle', '0004_auto_20180306_1624'),
        ('galerie_photo', '0009_auto_20180306_1611'),
        ('site_web', '0001_initial'),
        ('gestion_table', '0002_auto_20180307_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('galerie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galerie_photo.Theme')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_web.Site')),
                ('visite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visite_virtuelle.Visite')),
            ],
            options={
                'verbose_name': 'table',
            },
        ),
    ]
