# Generated by Django 2.0.2 on 2018-03-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_web', '0001_initial'),
        ('gestion_table', '0003_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='site',
        ),
        migrations.AddField(
            model_name='table',
            name='site',
            field=models.ManyToManyField(to='site_web.Site'),
        ),
    ]
