# Generated by Django 2.0.2 on 2018-03-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerie_photo', '0009_auto_20180306_1611'),
        ('gestion_table', '0004_auto_20180310_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='visite',
        ),
        migrations.RemoveField(
            model_name='table',
            name='galerie',
        ),
        migrations.AddField(
            model_name='table',
            name='galerie',
            field=models.ManyToManyField(to='galerie_photo.Photo'),
        ),
    ]
