# Generated by Django 2.0.2 on 2018-03-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galerie_photo', '0009_auto_20180306_1611'),
        ('visite_virtuelle', '0004_auto_20180306_1624'),
        ('gestion_table', '0007_remove_table_galerie'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='galerie',
            field=models.ManyToManyField(to='galerie_photo.Theme'),
        ),
        migrations.AddField(
            model_name='table',
            name='visite',
            field=models.ManyToManyField(to='visite_virtuelle.Visite'),
        ),
    ]
